# Setup
title:        How to write my own book
tagline:      Coaching to become the writer you want to be
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Leticia 
  url:        http://biodagar.com
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
