# Setup
title:        How can you write your own book?
tagline:      By working with a coach who gets it.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Leticia 
  url:        http://biodagar.com
# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
